Use property to define shellink name
cryptomator/integrations-win pull request #11
Opened 2022-05-09 15:21 UTC by infeo

This PR refactors the Autostart service impl to be more customizable.

The hard coded Cryptomator references are removed, instead the used shell link is named with the JVM property `org.cryptomator.integrations_win.autostart.shellinkname`.

2022-05-10 13:29 UTC, overheadhunter requested changes
* rename remaining occurances
* use snake_case for the system property itself

2022-05-10 13:29 UTC, overheadhunter commented on src/main/java/org/cryptomator/windows/autostart/WindowsAutoStart.java
> +		int returnCode = winShellLinks.createShortcut(exePath.get(), absoluteStartupEntryPath.toString(), getShellinkName());
```suggestion
		int returnCode = winShellLinks.createShortcut(exePath.get(), absoluteStartupEntryPath.toString(), getShellLinkName());
```

2022-05-10 13:29 UTC, overheadhunter commented on src/main/java/org/cryptomator/windows/autostart/WindowsAutoStart.java
> +			throw new ToggleAutoStartFailedException("Disabling auto start failed using startup folder: Name of shellink is not defined.");
```suggestion
			throw new ToggleAutoStartFailedException("Disabling auto start failed using startup folder: Name of shell link is not defined.");
```

2022-05-10 13:29 UTC, overheadhunter commented on src/main/java/org/cryptomator/windows/autostart/WindowsAutoStart.java
> +	private String getShellinkName() throws NoSuchElementException {
```suggestion
	private String getShellLinkName() throws NoSuchElementException {
```

2022-05-10 13:29 UTC, overheadhunter commented on src/main/java/org/cryptomator/windows/autostart/WindowsAutoStart.java
> +		this.absoluteStartupEntryPath = () -> Path.of(System.getProperty("user.home"), RELATIVE_STARTUP_FOLDER, this.getShellinkName() + LNK_FILE_EXTENSION).toAbsolutePath();
```suggestion
		this.absoluteStartupEntryPath = () -> Path.of(System.getProperty("user.home"), RELATIVE_STARTUP_FOLDER, this.getShellLinkName() + LNK_FILE_EXTENSION).toAbsolutePath();
```

2022-05-10 13:29 UTC, overheadhunter commented on src/main/java/org/cryptomator/windows/autostart/WindowsAutoStart.java
> +	private static final String LNK_NAME_PROPERTY = "org.cryptomator.integrations_win.autostart.shellLinkName";
```suggestion
	private static final String LNK_NAME_PROPERTY = "org.cryptomator.integrations_win.autostart.shell_link_name";
```

2022-05-10 13:29 UTC, overheadhunter commented on README.md
> +* `org.cryptomator.integrations_win.autostart.shellLinkName` - Name of the shell link, which is placed in the Windows startup folder to start application on user login
```suggestion
* `org.cryptomator.integrations_win.autostart.shell_link_name` - Name of the shell link, which is placed in the Windows startup folder to start application on user login
```

2022-05-10 14:44 UTC, overheadhunter requested changes
I'm wondering why changing an immutable value to something that the code suggests can change over time?

2022-05-10 14:44 UTC, overheadhunter commented on src/main/java/org/cryptomator/windows/autostart/WindowsAutoStart.java
> +	private String getShellLinkName() throws NoSuchElementException {
throwing a `NoSuchElementException` just because splitting a path doesn't work as expected is very rude.

2022-05-10 14:44 UTC, overheadhunter commented on src/main/java/org/cryptomator/windows/autostart/WindowsAutoStart.java
> +		);
Too much crammed into a single line. Less LoC doesn't mean more readable code.

2022-05-10 15:03 UTC, infeo commented
> I'm wondering why changing an immutable value to something that the code suggests can change over time?

We are using the [`ProcessHandle::info`](https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/lang/ProcessHandle.Info.html) API, which only return optionals. In case the system property is not set, the startup entry path depends on the presence of the exe path. If it is not present, accessing it throws a `NoSuchElementException`.

To be still able to initalize the object, instead of directly setting the startup entry path, a supplier is used computing it on demand.

2022-05-10 15:04 UTC, infeo commented
I'll see if i can use an optional instead.

2022-05-10 15:43 UTC, infeo commented
I added an additional variable and changed the type to Optional<...>. 
Additionally, the behaviour changed: Once an instance is created, the behaviour of this object won't change anymore.

2022-05-11 08:58 UTC, overheadhunter approved these changes

2022-05-11 09:02 UTC, merged