Replace GSON by Jackson
cryptomator/integrations-win pull request #23
Opened 2023-09-14 15:00 UTC by infeo

2023-09-14 20:08 UTC, overheadhunter requested changes
Looks good, just two minor code style CRs

2023-09-14 20:08 UTC, overheadhunter commented on src/main/java/org/cryptomator/windows/keychain/WindowsProtectedKeychainAccess.java
> +			}
Use different catch clauses instead

2023-09-14 20:08 UTC, overheadhunter commented on src/main/java/org/cryptomator/windows/keychain/WindowsProtectedKeychainAccess.java
> +			throw new KeychainAccessException("Could not read keychain from path " + keychainPath, ioe);
Unnecessary

2023-09-15 09:30 UTC, infeo commented on src/main/java/org/cryptomator/windows/keychain/WindowsProtectedKeychainAccess.java
> +			throw new KeychainAccessException("Could not read keychain from path " + keychainPath, ioe);
Fixed with https://github.com/cryptomator/integrations-win/pull/23/commits/0872aec65fff6b2764ba8454f0a1157ee2e69ad3

2023-09-15 09:30 UTC, infeo commented on src/main/java/org/cryptomator/windows/keychain/WindowsProtectedKeychainAccess.java
> +			}
Fixed with https://github.com/cryptomator/integrations-win/pull/23/commits/0872aec65fff6b2764ba8454f0a1157ee2e69ad3

2023-09-17 08:14 UTC, overheadhunter approved these changes

2023-09-17 19:59 UTC, merged